### ISSUE TITLE
Filesystem access popup issues

### ISSUE THREAD

**Issue by fwouts** [impulse-oss/impulse#1]
I'm trying out Impulse and I found a couple of minor issues with the filesystem access popup:

1. z-index should probably be higher so it shows up on top of everything else on a short screen:
![Screen Shot 2022-07-08 at 8 40 18 am](https://user-images.githubusercontent.com/772570/177884192-d8bbe83b-b6c3-4584-8fa9-05acc21a2d13.png)

2. tapping the "Enter" key does not automatically press "OK" as one would expect.

I was trying it out with [Preview.js](https://previewjs.com) and looks like unfortunately it won't be able to work as-is because of cross-origin iframe permission issues for the file picker when running inside VS Code, but looks promising nonetheless!

**Comment by kirillrogovoy** [comment]
Thanks for reporting that!

Fixed in 0.1.0 👍
