### ISSUE TITLE
Option+Click doesn't work on many sites/elements

### ISSUE THREAD

**Issue by vfonic** [impulse-oss/impulse#10]
Hi!

I just found this extension and I've been trying to set it up for [Arc browser](https://arc.net/) but with no success.

Any ideas?
It did show once, when I added a folder to a workspace in devtools under Sources => Filesystem.
I cannot repro this anymore. I don't know why.

In the devtools console I get this consistently:
> Impulse started successfully! 🎉 {version: '0.4.5'}

Here's Arc invite code if you need one (they limited this to 5 invites):
https://arc.net/gift/46c73abb

**Comment by kirillrogovoy** [comment]
Hey,

Just to make sure that it's a browser issue — does it work well for you in Chrome?

**Comment by vfonic** [comment]
Hmmmm, I just tested it on https://impulse.dev/ and it works in all three browsers. 🎉 
However, I cannot get it to work on pretty much any other website.

Tried on:
GitHub (doesn't allow loading the script)
HubSpot (same)
Hacker News (same)

ClickUp - loads the script, but Option+Click doesn't activate the extension. (`.text-theme-content` div is empty)
DigitalOcean (same as above)
https://techcrunch.com/ (same)
Some of my own webapps (same)

I'll try disabling all extensions and see what happens.

**Comment by vfonic** [comment]
I disabled all extensions, but it doesn't seem like it's an extensions issue, but Impulse issue. Impulse doesn't work on most of the elements I tried to click on.
I'm loading Impulse by pasting this in the browser console:
`d=document;s=d.createElement('script');s.src=`https://cdn.jsdelivr.net/npm/@impulse.dev/runtime@latest/inject.js`;d.body.appendChild(s)`

Then I click on page elements with Option+Click.

For example on this page: https://www.digitalocean.com/ I cannot click on the text below 99.99%, but I can click on 99.99% or most of the other text on the page. It seems like it doesn't work on most of the websites/places that I've tried to click.

I also tried on Heroku login page and some other "simple" sites.
What do you think why these pages/elements don't work?
Am I doing something wrong?

**Comment by kirillrogovoy** [comment]
Oh, I see. Impulse was created only to work with React websites _in dev mode_ (meaning, running on your `localhost`).

While it could potentially work on external websites, it would not be doing anything useful.

Its main purpose is to allow you to seamlessly jump between the website and the code, and to edit Tailwind classes on the website while automatically editing your code.

**Comment by vfonic** [comment]
Ahhhhh so that's why it's not working! :)

Thanks for the explanation!

I'll add some of this to the README.md so feel free to merge it if you believe there's a value to it.

**Comment by vfonic** [comment]
Speaking of impulse.dev, perhaps you could include Impulse there so people can try out the tool a bit before committing to installing it. Just a wild thought.
People could clone the impulse.dev repo and connect to their editor to try out the demo of how the tool works.

That being said, with sourcemaps, it could make sense to have the tool working for non-localhost sites in some cases...I guess.
