### ISSUE TITLE
[feature request] dom-tree minimap 

### ISSUE THREAD

**Issue by cocoonkid** [impulse-oss/impulse#2]
It'd be super helpful to have an minimap on the left side which shows the users position within the domtree. 

This minimap should sync the motions of jumping around inside the nested tree.

And allow for a zoom functionality.

This might make or make no sense at all :-)

**Comment by kirillrogovoy** [comment]
Hey,

Thanks for the suggestion!

This is one of the big UI things I'm planning on implementing. Feel free to share any additional details on what you imagine that would look like!

**Comment by cocoonkid** [comment]
@kirillrogovoy ❤️
