### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by Geczy** [impulse-oss/impulse#3]
running the one liner ```d=document;s=d.createElement('script');s.src=`https://cdn.jsdelivr.net/npm/@impulse.dev/runtime@latest/inject.js?${Date.now()}`;d.body.appendChild(s)```

produces:

Uncaught ReferenceError: process is not defined
    at index.js:3:17
    at jsdelivr-header.js:7:1
    at jsdelivr-header.js:7:1
(anonymous) @ index.js:3
(anonymous) @ jsdelivr-header.js:7
(anonymous) @ jsdelivr-header.js:7

inject.js?1658788569136:5 Uncaught ReferenceError: IMPULSE_RUN is not defined
    at s.onload (inject.js?1658788569136:5:18)

**Comment by kirillrogovoy** [comment]
Thanks for reporting!

Fixed now. 🎉 

Let me know if it still happens.
