### ISSUE TITLE
[Bug] setting text color in body can make editor unreadable

### ISSUE THREAD

**Issue by abb128** [impulse-oss/impulse#4]
Hi, this is looking like a cool tool so far!

I tried testing it out on one of my existing pages through the quick "try now" browser console option. The editor was completely unreadable:

![image](https://user-images.githubusercontent.com/65567823/184019955-23f80ac2-dfc6-4680-b79b-0a8e9e00cdc4.png)

My HTML body tag contains the text-emerald-100 class. Manually removing this in Inspect Element made the editor readable. Example: `<body class="text-emerald-100">`.

I believe a quick way to ignore all parent styling would be to use `all: initial;` CSS style. Also, it might be a good idea to move the editor into a shadow root.

**Comment by kirillrogovoy** [comment]
Hey, thanks for submitting the issue!

Should be trivial to fix. I'll look into it and let you know. 🙌
